<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_Xb3KSzuService extends KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.xb3KSzu' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        $a = ($container->privates['Akeneo\\Catalogs\\Application\\Handler\\GetProductUuidsHandler'] ?? $container->load('getGetProductUuidsHandlerService'));

        if (isset($container->privates['.messenger.handler_descriptor.xb3KSzu'])) {
            return $container->privates['.messenger.handler_descriptor.xb3KSzu'];
        }

        return $container->privates['.messenger.handler_descriptor.xb3KSzu'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor($a, []);
    }
}
