<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_MethodOnObjectWrapper_9_D_IGsService extends KernelProdContainer
{
    /*
     * Gets the private '.messenger.method_on_object_wrapper.9.d.iGs' shared service.
     *
     * @return \Closure
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.method_on_object_wrapper.9.d.iGs'] = \Closure::fromCallable([0 => ($container->privates['Akeneo\\Tool\\Bundle\\BatchQueueBundle\\MessageHandler\\JobMessageHandler'] ?? $container->load('getJobMessageHandlerService')), 1 => 'handleJobExecution']);
    }
}
