<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_MRr8e6mService extends KernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.MRr8e6m' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';

        return $container->privates['.messenger.handler_descriptor.MRr8e6m'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['.messenger.method_on_object_wrapper.JIErdn2'] ?? $container->load('get_Messenger_MethodOnObjectWrapper_JIErdn2Service')), ['method' => 'handleScheduledJob']);
    }
}
