<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Akeneo_Platform_Command_Install_LazyService extends KernelProdContainer
{
    /*
     * Gets the private '.akeneo.platform.command.install.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.akeneo.platform.command.install.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pim:install', [], 'Akeneo PIM Application Installer.', false, function () use ($container): \Akeneo\Platform\Bundle\InstallerBundle\Command\InstallCommand {
            return ($container->privates['akeneo.platform.command.install'] ?? $container->load('getAkeneo_Platform_Command_InstallService'));
        });
    }
}
