<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoBatch_Validator_JobInstance_SchedulingService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo_batch.validator.job_instance.scheduling' shared service.
     *
     * @return \Akeneo\Tool\Bundle\BatchBundle\Validator\Constraints\DummySchedulingValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Validator/Constraints/DummySchedulingValidator.php';

        return $container->privates['akeneo_batch.validator.job_instance.scheduling'] = new \Akeneo\Tool\Bundle\BatchBundle\Validator\Constraints\DummySchedulingValidator();
    }
}
