<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Pim_Automation_DataQualityInsights_Query_GetProductModelCriteriaEvaluationsService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations' shared service.
     *
     * @return \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetCriteriaEvaluationsByEntityIdQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetCriteriaEvaluationsByEntityIdQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetCriteriaEvaluationsByEntityIdQuery.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Clock.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Clock/SystemClock.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'])) {
            return $container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'];
        }
        $b = ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Persistence\\Transformation\\TransformCriterionEvaluationResultIds'] ?? $container->load('getTransformCriterionEvaluationResultIdsService'));

        if (isset($container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'])) {
            return $container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'];
        }

        return $container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'] = new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetCriteriaEvaluationsByEntityIdQuery($a, ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Clock\\SystemClock'] ?? ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Clock\\SystemClock'] = new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Clock\SystemClock())), $b, 'pim_data_quality_insights_product_model_criteria_evaluation');
    }
}
