<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Pim_Enrichment_Product_Query_SaveProductCompletenessesService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.pim.enrichment.product.query.save_product_completenesses' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Storage\Sql\Completeness\SqlSaveProductCompletenesses
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/SaveProductCompletenesses.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/SqlSaveProductCompletenesses.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['akeneo.pim.enrichment.product.query.save_product_completenesses'])) {
            return $container->privates['akeneo.pim.enrichment.product.query.save_product_completenesses'];
        }

        return $container->privates['akeneo.pim.enrichment.product.query.save_product_completenesses'] = new \Akeneo\Pim\Enrichment\Bundle\Storage\Sql\Completeness\SqlSaveProductCompletenesses($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
