<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoMeasure_Controller_Rest_MeasuresService extends KernelProdContainer
{
    /*
     * Gets the public 'akeneo_measure.controller.rest.measures' shared service.
     *
     * @return \Akeneo\Tool\Bundle\MeasureBundle\Controller\MeasuresController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/MeasureBundle/Controller/MeasuresController.php';

        return $container->services['akeneo_measure.controller.rest.measures'] = new \Akeneo\Tool\Bundle\MeasureBundle\Controller\MeasuresController(($container->privates['akeneo_measure.persistence.measurement_family_repository'] ?? $container->load('getAkeneoMeasure_Persistence_MeasurementFamilyRepositoryService')), ($container->privates['akeneo.pim.structure.query.is_there_at_least_one_attribute_configured_with_measurement_family'] ?? $container->load('getAkeneo_Pim_Structure_Query_IsThereAtLeastOneAttributeConfiguredWithMeasurementFamilyService')));
    }
}
