<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoElasticsearch_Install_InstallSubscriberService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo_elasticsearch.install.install_subscriber' shared service.
     *
     * @return \Akeneo\Tool\Bundle\ElasticsearchBundle\Infrastructure\Install\InstallSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Infrastructure/Install/InstallSubscriber.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['akeneo_elasticsearch.install.install_subscriber'])) {
            return $container->privates['akeneo_elasticsearch.install.install_subscriber'];
        }

        return $container->privates['akeneo_elasticsearch.install.install_subscriber'] = new \Akeneo\Tool\Bundle\ElasticsearchBundle\Infrastructure\Install\InstallSubscriber($a);
    }
}
