<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Pim_Enrichment_Completeness_MaskItemGenerator_PriceCollectionService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.pim.enrichment.completeness.mask_item_generator.price_collection' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Completeness\MaskItemGenerator\PriceCollectionMaskItemGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/MaskItemGeneratorForAttributeType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Completeness/MaskItemGenerator/PriceCollectionMaskItemGenerator.php';

        return $container->privates['akeneo.pim.enrichment.completeness.mask_item_generator.price_collection'] = new \Akeneo\Pim\Enrichment\Component\Product\Completeness\MaskItemGenerator\PriceCollectionMaskItemGenerator(($container->privates['pim_catalog.query.find_activated_currencies'] ?? $container->load('getPimCatalog_Query_FindActivatedCurrenciesService')));
    }
}
