<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Platform_Command_InstallService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.platform.command.install' shared service.
     *
     * @return \Akeneo\Platform\Bundle\InstallerBundle\Command\InstallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/InstallerBundle/Command/InstallCommand.php';

        $container->privates['akeneo.platform.command.install'] = $instance = new \Akeneo\Platform\Bundle\InstallerBundle\Command\InstallCommand(($container->privates['pim_installer.install_status_manager'] ?? $container->load('getPimInstaller_InstallStatusManagerService')));

        $instance->setName('pim:install');
        $instance->setDescription('Akeneo PIM Application Installer.');

        return $instance;
    }
}
