<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Pim_Automation_DataQualityInsights_Query_ComputeProductModelsWithImageQueryService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query' shared service.
     *
     * @return \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\KeyIndicator\ComputeProductsWithImageQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/Dashboard/ComputeProductsKeyIndicator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/KeyIndicator/ComputeProductsWithImageQuery.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetEvaluationRatesByProductsAndCriterionQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetEvaluationRatesByProductModelsAndCriterionQuery.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query'])) {
            return $container->privates['akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query'];
        }
        $b = ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Persistence\\Transformation\\TransformCriterionEvaluationResultIds'] ?? $container->load('getTransformCriterionEvaluationResultIdsService'));

        if (isset($container->privates['akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query'])) {
            return $container->privates['akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query'];
        }

        return $container->privates['akeneo.pim.automation.data_quality_insights.query.compute_product_models_with_image_query'] = new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\KeyIndicator\ComputeProductsWithImageQuery(new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetEvaluationRatesByProductModelsAndCriterionQuery($a, $b));
    }
}
