<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoFileStorage_Form_Type_FileInfoService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo_file_storage.form.type.file_info' shared service.
     *
     * @return \Akeneo\Tool\Bundle\FileStorageBundle\Form\Type\FileInfoType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/FileStorageBundle/Form/Type/FileInfoType.php';

        return $container->privates['akeneo_file_storage.form.type.file_info'] = new \Akeneo\Tool\Bundle\FileStorageBundle\Form\Type\FileInfoType('Akeneo\\Tool\\Component\\FileStorage\\Model\\FileInfo');
    }
}
