<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_FeatureFlag_Service_ControllerService extends KernelProdContainer
{
    /*
     * Gets the public 'akeneo.feature_flag.service.controller' shared service.
     *
     * @return \Akeneo\Platform\Bundle\FeatureFlagBundle\Internal\Controller
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/FeatureFlagBundle/Internal/Controller.php';

        return $container->services['akeneo.feature_flag.service.controller'] = new \Akeneo\Platform\Bundle\FeatureFlagBundle\Internal\Controller(($container->services['feature_flags'] ?? $container->getFeatureFlagsService()));
    }
}
