<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoBatch_LoadJobParametersListenerService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo_batch.load_job_parameters_listener' shared service.
     *
     * @return \Akeneo\Tool\Bundle\BatchBundle\EventListener\LoadJobParametersListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/EventListener/LoadJobParametersListener.php';

        $a = ($container->privates['akeneo_batch.job_parameters_factory'] ?? $container->load('getAkeneoBatch_JobParametersFactoryService'));

        if (isset($container->privates['akeneo_batch.load_job_parameters_listener'])) {
            return $container->privates['akeneo_batch.load_job_parameters_listener'];
        }

        return $container->privates['akeneo_batch.load_job_parameters_listener'] = new \Akeneo\Tool\Bundle\BatchBundle\EventListener\LoadJobParametersListener($a);
    }
}
