<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneoMeasurement_Validation_DeleteMeasurementFamily_ShouldNotBeUsedByProductAttributeService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo_measurement.validation.delete_measurement_family.should_not_be_used_by_product_attribute' shared service.
     *
     * @return \Akeneo\Tool\Bundle\MeasureBundle\Validation\DeleteMeasurementFamily\ShouldNotBeUsedByProductAttributeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/MeasureBundle/Validation/DeleteMeasurementFamily/ShouldNotBeUsedByProductAttributeValidator.php';

        $a = ($container->privates['akeneo.pim.structure.query.is_there_at_least_one_attribute_configured_with_measurement_family'] ?? $container->load('getAkeneo_Pim_Structure_Query_IsThereAtLeastOneAttributeConfiguredWithMeasurementFamilyService'));

        if (isset($container->privates['akeneo_measurement.validation.delete_measurement_family.should_not_be_used_by_product_attribute'])) {
            return $container->privates['akeneo_measurement.validation.delete_measurement_family.should_not_be_used_by_product_attribute'];
        }

        return $container->privates['akeneo_measurement.validation.delete_measurement_family.should_not_be_used_by_product_attribute'] = new \Akeneo\Tool\Bundle\MeasureBundle\Validation\DeleteMeasurementFamily\ShouldNotBeUsedByProductAttributeValidator($a);
    }
}
