<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAkeneo_Pim_Enrichment_Factory_Value_FileService extends KernelProdContainer
{
    /*
     * Gets the private 'akeneo.pim.enrichment.factory.value.file' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Factory\Value\FileValueFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/ValueFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/Value/FileValueFactory.php';

        $a = ($container->privates['akeneo_file_storage.repository.file_info'] ?? $container->load('getAkeneoFileStorage_Repository_FileInfoService'));

        if (isset($container->privates['akeneo.pim.enrichment.factory.value.file'])) {
            return $container->privates['akeneo.pim.enrichment.factory.value.file'];
        }

        return $container->privates['akeneo.pim.enrichment.factory.value.file'] = new \Akeneo\Pim\Enrichment\Component\Product\Factory\Value\FileValueFactory($a);
    }
}
