<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBooleanProductValueRendererService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Bundle\PdfGeneration\Renderer\ProductValueRenderer\BooleanProductValueRenderer' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\PdfGeneration\Renderer\ProductValueRenderer\BooleanProductValueRenderer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/ProductValueRenderer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/PdfGeneration/Renderer/ProductValueRenderer/BooleanProductValueRenderer.php';

        return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\PdfGeneration\\Renderer\\ProductValueRenderer\\BooleanProductValueRenderer'] = new \Akeneo\Pim\Enrichment\Bundle\PdfGeneration\Renderer\ProductValueRenderer\BooleanProductValueRenderer(($container->services['translator'] ?? $container->getTranslatorService()));
    }
}
