<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateOpenIdKeysCommandService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Infrastructure\Apps\Command\CreateOpenIdKeysCommand' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\Apps\Command\CreateOpenIdKeysCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Apps/Command/CreateOpenIdKeysCommand.php';

        $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Apps\\Command\\CreateOpenIdKeysCommand'] = $instance = new \Akeneo\Connectivity\Connection\Infrastructure\Apps\Command\CreateOpenIdKeysCommand(($container->privates['Akeneo\\Connectivity\\Connection\\Application\\Apps\\Command\\GenerateAsymmetricKeysHandler'] ?? $container->load('getGenerateAsymmetricKeysHandlerService')));

        $instance->setName('akeneo:connectivity-connection:openid-keys:create');
        $instance->setDescription('Create or update a public/private key couple to be used to sign openid token and store it into database');

        return $instance;
    }
}
