<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCategoryTranslationsSaverService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Category\Application\Storage\Save\Saver\CategoryTranslationsSaver' shared service.
     *
     * @return \Akeneo\Category\Application\Storage\Save\Saver\CategoryTranslationsSaver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Application/Storage/Save/Saver/CategorySaver.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Application/Storage/Save/Saver/CategoryTranslationsSaver.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Application/Storage/Save/Query/UpsertCategoryTranslations.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Infrastructure/Storage/Save/Query/UpsertCategoryTranslationsSql.php';

        return $container->privates['Akeneo\\Category\\Application\\Storage\\Save\\Saver\\CategoryTranslationsSaver'] = new \Akeneo\Category\Application\Storage\Save\Saver\CategoryTranslationsSaver(new \Akeneo\Category\Infrastructure\Storage\Save\Query\UpsertCategoryTranslationsSql(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()), ($container->privates['Akeneo\\Category\\Domain\\Query\\GetCategoryInterface'] ?? $container->load('getGetCategoryInterfaceService'))), [0 => 'Akeneo\\Category\\Api\\Command\\UserIntents\\SetLabel']);
    }
}
