<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeleteUserService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Infrastructure\Service\User\DeleteUser' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\Service\User\DeleteUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Settings/Service/DeleteUserInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/User/DeleteUser.php';

        return $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Service\\User\\DeleteUser'] = new \Akeneo\Connectivity\Connection\Infrastructure\Service\User\DeleteUser(($container->privates['pim_user.repository.user'] ?? $container->load('getPimUser_Repository_UserService')), ($container->privates['pim_user.remover.user'] ?? $container->load('getPimUser_Remover_UserService')));
    }
}
