<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDispatchReadProductEventFromEventsApiSubscriberService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EventsApi\DispatchReadProductEventFromEventsApiSubscriber' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EventsApi\DispatchReadProductEventFromEventsApiSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EventsApi/DispatchReadProductEventFromEventsApiSubscriber.php';

        $a = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\EventsApi\\DispatchReadProductEventFromEventsApiSubscriber'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\EventsApi\\DispatchReadProductEventFromEventsApiSubscriber'];
        }

        return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\EventsApi\\DispatchReadProductEventFromEventsApiSubscriber'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EventsApi\DispatchReadProductEventFromEventsApiSubscriber($a);
    }
}
