<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExternalUrlValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Application\Webhook\Validation\ExternalUrlValidator' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Application\Webhook\Validation\ExternalUrlValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/ExternalUrlValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/DnsLookupInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/DnsLookup.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Webhook/Service/IpMatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/IpMatcher.php';

        return $container->privates['Akeneo\\Connectivity\\Connection\\Application\\Webhook\\Validation\\ExternalUrlValidator'] = new \Akeneo\Connectivity\Connection\Application\Webhook\Validation\ExternalUrlValidator(new \Akeneo\Connectivity\Connection\Infrastructure\Service\DnsLookup(), new \Akeneo\Connectivity\Connection\Infrastructure\Service\IpMatcher(), $container->getEnv('string:ALLOWED_NETWORK_WHITELIST'));
    }
}
