<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventSubscriptionsLimitValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Application\Webhook\Validation\EventSubscriptionsLimitValidator' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Application\Webhook\Validation\EventSubscriptionsLimitValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Webhook/Validation/EventSubscriptionsLimitValidator.php';

        $a = ($container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Webhook\\Persistence\\DbalSelectActiveWebhooksQuery'] ?? $container->load('getDbalSelectActiveWebhooksQueryService'));

        if (isset($container->privates['Akeneo\\Connectivity\\Connection\\Application\\Webhook\\Validation\\EventSubscriptionsLimitValidator'])) {
            return $container->privates['Akeneo\\Connectivity\\Connection\\Application\\Webhook\\Validation\\EventSubscriptionsLimitValidator'];
        }

        return $container->privates['Akeneo\\Connectivity\\Connection\\Application\\Webhook\\Validation\\EventSubscriptionsLimitValidator'] = new \Akeneo\Connectivity\Connection\Application\Webhook\Validation\EventSubscriptionsLimitValidator($a, 3);
    }
}
