<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFindAConnectionHandlerService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Application\Settings\Query\FindAConnectionHandler' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Application\Settings\Query\FindAConnectionHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Settings/Query/FindAConnectionHandler.php';

        return $container->privates['Akeneo\\Connectivity\\Connection\\Application\\Settings\\Query\\FindAConnectionHandler'] = new \Akeneo\Connectivity\Connection\Application\Settings\Query\FindAConnectionHandler(($container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Settings\\Persistence\\DbalSelectConnectionWithCredentialsByCodeQuery'] ?? $container->load('getDbalSelectConnectionWithCredentialsByCodeQueryService')));
    }
}
