<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFilterContainsValidChannelValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Catalogs\Infrastructure\Validation\ProductValueFilters\FilterContainsValidChannelValidator' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Validation\ProductValueFilters\FilterContainsValidChannelValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Validation/ProductValueFilters/FilterContainsValidChannelValidator.php';

        return $container->privates['Akeneo\\Catalogs\\Infrastructure\\Validation\\ProductValueFilters\\FilterContainsValidChannelValidator'] = new \Akeneo\Catalogs\Infrastructure\Validation\ProductValueFilters\FilterContainsValidChannelValidator(($container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Channel\\GetChannelQuery'] ?? $container->load('getGetChannelQueryService')));
    }
}
