<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFosRest_SerializerService extends KernelProdContainer
{
    /*
     * Gets the private 'fos_rest.serializer' shared service.
     *
     * @return \FOS\RestBundle\Serializer\SymfonySerializerAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Serializer/Serializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/friendsofsymfony/rest-bundle/Serializer/SymfonySerializerAdapter.php';

        return $container->privates['fos_rest.serializer'] = new \FOS\RestBundle\Serializer\SymfonySerializerAdapter(($container->privates['pim_external_api_exception_serializer'] ?? $container->load('getPimExternalApiExceptionSerializerService')));
    }
}
