<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFamilyCriterionContainsValidFamiliesValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Catalogs\Infrastructure\Validation\ProductSelection\FamilyCriterionContainsValidFamiliesValidator' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Validation\ProductSelection\FamilyCriterionContainsValidFamiliesValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Validation/ProductSelection/FamilyCriterionContainsValidFamiliesValidator.php';

        $a = ($container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Family\\GetFamiliesByCodeQuery'] ?? $container->load('getGetFamiliesByCodeQueryService'));

        if (isset($container->privates['Akeneo\\Catalogs\\Infrastructure\\Validation\\ProductSelection\\FamilyCriterionContainsValidFamiliesValidator'])) {
            return $container->privates['Akeneo\\Catalogs\\Infrastructure\\Validation\\ProductSelection\\FamilyCriterionContainsValidFamiliesValidator'];
        }

        return $container->privates['Akeneo\\Catalogs\\Infrastructure\\Validation\\ProductSelection\\FamilyCriterionContainsValidFamiliesValidator'] = new \Akeneo\Catalogs\Infrastructure\Validation\ProductSelection\FamilyCriterionContainsValidFamiliesValidator($a);
    }
}
