<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetProductModelEvaluationControllerService extends KernelProdContainer
{
    /*
     * Gets the public 'Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Symfony\Controller\GetProductModelEvaluationController' shared service.
     *
     * @return \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Symfony\Controller\GetProductModelEvaluationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Symfony/Controller/GetProductModelEvaluationController.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/GetProductEvaluation.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Domain/Query/ProductEvaluation/GetCriteriaEvaluationsByEntityIdQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Persistence/Query/ProductEvaluation/GetUpToDateCriteriaEvaluationsByEntityIdQuery.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEvaluation/CompleteEvaluationWithImprovableAttributes.php';

        $a = ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Persistence\\Query\\Structure\\CachedGetLocalesByChannelQuery'] ?? $container->load('getCachedGetLocalesByChannelQueryService'));

        return $container->services['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Symfony\\Controller\\GetProductModelEvaluationController'] = new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Symfony\Controller\GetProductModelEvaluationController(new \Akeneo\Pim\Automation\DataQualityInsights\Application\GetProductEvaluation(new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Persistence\Query\ProductEvaluation\GetUpToDateCriteriaEvaluationsByEntityIdQuery(($container->privates['akeneo.pim.automation.data_quality_insights.query.get_product_model_criteria_evaluations'] ?? $container->load('getAkeneo_Pim_Automation_DataQualityInsights_Query_GetProductModelCriteriaEvaluationsService')), ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Persistence\\Query\\ProductEvaluation\\HasUpToDateProductModelEvaluationQuery'] ?? $container->load('getHasUpToDateProductModelEvaluationQueryService'))), $a, ($container->privates['akeneo.pim.automation.data_quality_insights.product_model_criteria_by_feature_registry'] ?? $container->load('getAkeneo_Pim_Automation_DataQualityInsights_ProductModelCriteriaByFeatureRegistryService')), new \Akeneo\Pim\Automation\DataQualityInsights\Application\ProductEvaluation\CompleteEvaluationWithImprovableAttributes($a, ($container->privates['akeneo.pim.automation.calculate_product_model_completeness_of_required_attributes'] ?? $container->load('getAkeneo_Pim_Automation_CalculateProductModelCompletenessOfRequiredAttributesService')), ($container->privates['akeneo.pim.automation.calculate_product_model_completeness_of_non_required_attributes'] ?? $container->load('getAkeneo_Pim_Automation_CalculateProductModelCompletenessOfNonRequiredAttributesService')))));
    }
}
