<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetLocalesByCodeQueryService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Catalogs\Infrastructure\Persistence\Locale\GetLocalesByCodeQuery' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Persistence\Locale\GetLocalesByCodeQuery
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Application/Persistence/Locale/GetLocalesByCodeQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Persistence/Locale/GetLocalesByCodeQuery.php';

        return $container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Locale\\GetLocalesByCodeQuery'] = new \Akeneo\Catalogs\Infrastructure\Persistence\Locale\GetLocalesByCodeQuery(($container->privates['pim_catalog.repository.locale'] ?? $container->getPimCatalog_Repository_LocaleService()));
    }
}
