<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetChannelActionService extends KernelProdContainer
{
    /*
     * Gets the public 'Akeneo\Catalogs\Infrastructure\Controller\Internal\GetChannelAction' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Controller\Internal\GetChannelAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Controller/Internal/GetChannelAction.php';

        return $container->services['Akeneo\\Catalogs\\Infrastructure\\Controller\\Internal\\GetChannelAction'] = new \Akeneo\Catalogs\Infrastructure\Controller\Internal\GetChannelAction(($container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Channel\\GetChannelQuery'] ?? $container->load('getGetChannelQueryService')));
    }
}
