<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGetAttributesActionService extends KernelProdContainer
{
    /*
     * Gets the public 'Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAttributesAction' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAttributesAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Controller/Internal/GetAttributesAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Application/Persistence/Attribute/SearchAttributesQueryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Persistence/Attribute/SearchAttributesQuery.php';

        return $container->services['Akeneo\\Catalogs\\Infrastructure\\Controller\\Internal\\GetAttributesAction'] = new \Akeneo\Catalogs\Infrastructure\Controller\Internal\GetAttributesAction(new \Akeneo\Catalogs\Infrastructure\Persistence\Attribute\SearchAttributesQuery(($container->privates['pim_enrich.repository.attribute.search'] ?? $container->load('getPimEnrich_Repository_Attribute_SearchService'))));
    }
}
