<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInitializeEvaluationOfAProductSubscriberService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Subscriber\Product\InitializeEvaluationOfAProductSubscriber' shared service.
     *
     * @return \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Subscriber\Product\InitializeEvaluationOfAProductSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Infrastructure/Subscriber/Product/InitializeEvaluationOfAProductSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductEntityIdFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/ProductUuidFactory.php';

        $a = ($container->services['akeneo.pim.automation.data_quality_insights.create_products_criteria_evaluations'] ?? $container->load('getAkeneo_Pim_Automation_DataQualityInsights_CreateProductsCriteriaEvaluationsService'));

        if (isset($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Subscriber\\Product\\InitializeEvaluationOfAProductSubscriber'])) {
            return $container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Subscriber\\Product\\InitializeEvaluationOfAProductSubscriber'];
        }

        return $container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Subscriber\\Product\\InitializeEvaluationOfAProductSubscriber'] = new \Akeneo\Pim\Automation\DataQualityInsights\Infrastructure\Subscriber\Product\InitializeEvaluationOfAProductSubscriber(($container->services['akeneo.pim.automation.data_quality_insights.feature'] ?? ($container->services['akeneo.pim.automation.data_quality_insights.feature'] = new \Akeneo\Platform\Bundle\FeatureFlagBundle\Configuration\EnvVarFeatureFlag($container->getEnv('bool:FLAG_DATA_QUALITY_INSIGHTS_ENABLED')))), $a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Application\\ProductUuidFactory'] ?? ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Application\\ProductUuidFactory'] = new \Akeneo\Pim\Automation\DataQualityInsights\Application\ProductUuidFactory())));
    }
}
