<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageLoaderService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Category\Infrastructure\FileSystem\Loader\ImageLoader' shared service.
     *
     * @return \Akeneo\Category\Infrastructure\FileSystem\Loader\ImageLoader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/liip/imagine-bundle/Binary/Loader/LoaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Infrastructure/FileSystem/Loader/ImageLoader.php';

        return $container->privates['Akeneo\\Category\\Infrastructure\\FileSystem\\Loader\\ImageLoader'] = new \Akeneo\Category\Infrastructure\FileSystem\Loader\ImageLoader(($container->privates['mime_types'] ?? $container->load('getMimeTypesService')), ($container->services['oneup_flysystem.category_storage_filesystem'] ?? $container->load('getOneupFlysystem_CategoryStorageFilesystemService')));
    }
}
