<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJobExecutionWatchdogCommand_LazyService extends KernelProdContainer
{
    /*
     * Gets the private '.Akeneo\Tool\Bundle\BatchQueueBundle\Command\JobExecutionWatchdogCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Akeneo\\Tool\\Bundle\\BatchQueueBundle\\Command\\JobExecutionWatchdogCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('akeneo:batch:watchdog', [], '[Internal] Launched by the job queue consumer', false, function () use ($container): \Akeneo\Tool\Bundle\BatchQueueBundle\Command\JobExecutionWatchdogCommand {
            return ($container->privates['Akeneo\\Tool\\Bundle\\BatchQueueBundle\\Command\\JobExecutionWatchdogCommand'] ?? $container->load('getJobExecutionWatchdogCommandService'));
        });
    }
}
