<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaleShouldBeEditableByUserValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleShouldBeEditableByUserValidator' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleShouldBeEditableByUserValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/LocaleShouldBeEditableByUserValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/back/API/Query/IsLocaleEditable.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/back/Infrastructure/Query/DummyIsLocaleEditable.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleShouldBeEditableByUserValidator'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleShouldBeEditableByUserValidator'];
        }

        return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleShouldBeEditableByUserValidator'] = new \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleShouldBeEditableByUserValidator(new \Akeneo\Channel\Infrastructure\Query\DummyIsLocaleEditable($a));
    }
}
