<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaleAndChannelShouldBeConsistentValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleAndChannelShouldBeConsistentValidator' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleAndChannelShouldBeConsistentValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/LocaleAndChannelShouldBeConsistentValidator.php';

        $a = ($container->privates['akeneo.pim.structure.query.get_attributes'] ?? $container->load('getAkeneo_Pim_Structure_Query_GetAttributesService'));

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleAndChannelShouldBeConsistentValidator'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleAndChannelShouldBeConsistentValidator'];
        }
        $b = ($container->privates['pim_channel.query.cache.channel_exists_with_locale'] ?? $container->load('getPimChannel_Query_Cache_ChannelExistsWithLocaleService'));

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleAndChannelShouldBeConsistentValidator'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleAndChannelShouldBeConsistentValidator'];
        }

        return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\LocaleAndChannelShouldBeConsistentValidator'] = new \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\LocaleAndChannelShouldBeConsistentValidator($a, $b);
    }
}
