<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLegacyPimApi_Controller_MeasureFamilyService extends KernelProdContainer
{
    /*
     * Gets the public 'legacy_pim_api.controller.measure_family' shared service.
     *
     * @return \Akeneo\Tool\Bundle\MeasureBundle\Controller\ExternalApi\LegacyMeasureFamilyController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/LegacyMeasureFamilyController.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/ArrayConverter/ArrayConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Api/Converter/MeasureFamilyConverter.php';

        return $container->services['legacy_pim_api.controller.measure_family'] = new \Akeneo\Tool\Bundle\MeasureBundle\Controller\ExternalApi\LegacyMeasureFamilyController(new \Akeneo\Tool\Component\Api\Converter\MeasureFamilyConverter(), ($container->privates['pim_api.pagination.parameter_validator'] ?? $container->load('getPimApi_Pagination_ParameterValidatorService')), ($container->privates['pim_api.pagination.offset_hal_paginator'] ?? $container->load('getPimApi_Pagination_OffsetHalPaginatorService')), ($container->privates['akeneo_measure.provider.measurement_provider'] ?? $container->load('getAkeneoMeasure_Provider_MeasurementProviderService')), $container->parameters['pim_api.configuration']);
    }
}
