<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getListClientsCommand_LazyService extends KernelProdContainer
{
    /*
     * Gets the private '.Akeneo\Tool\Bundle\ApiBundle\Command\ListClientsCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.Akeneo\\Tool\\Bundle\\ApiBundle\\Command\\ListClientsCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('pim:oauth-server:list-clients', [], 'Lists all existing pairs of client id / secret for the web API', false, function () use ($container): \Akeneo\Tool\Bundle\ApiBundle\Command\ListClientsCommand {
            return ($container->privates['Akeneo\\Tool\\Bundle\\ApiBundle\\Command\\ListClientsCommand'] ?? $container->load('getListClientsCommandService'));
        });
    }
}
