<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMigrateJobExecutionWarningCountCommandService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Tool\Bundle\BatchBundle\Command\MigrateJobExecutionWarningCountCommand' shared service.
     *
     * @return \Akeneo\Tool\Bundle\BatchBundle\Command\MigrateJobExecutionWarningCountCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/BatchBundle/Command/MigrateJobExecutionWarningCountCommand.php';

        $container->privates['Akeneo\\Tool\\Bundle\\BatchBundle\\Command\\MigrateJobExecutionWarningCountCommand'] = $instance = new \Akeneo\Tool\Bundle\BatchBundle\Command\MigrateJobExecutionWarningCountCommand(($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()));

        $instance->setName('akeneo:batch:migrate-job-execution-warning-count');

        return $instance;
    }
}
