<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessenger_Transport_ScheduledJobService extends KernelProdContainer
{
    /*
     * Gets the private 'messenger.transport.scheduled_job' shared service.
     *
     * @return \Symfony\Component\Messenger\Transport\TransportInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Receiver/ReceiverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/Sender/SenderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Transport/TransportInterface.php';

        $a = ($container->privates['messenger.transport_factory'] ?? $container->load('getMessenger_TransportFactoryService'));

        if (isset($container->privates['messenger.transport.scheduled_job'])) {
            return $container->privates['messenger.transport.scheduled_job'];
        }

        return $container->privates['messenger.transport.scheduled_job'] = $a->createTransport('doctrine://default', ['table_name' => 'messenger_messages', 'queue_name' => 'scheduled_job', 'redeliver_timeout' => 86400, 'auto_setup' => false, 'transport_name' => 'scheduled_job'], ($container->privates['akeneo_batch_queue.messenger.serializer'] ?? $container->load('getAkeneoBatchQueue_Messenger_SerializerService')));
    }
}
