<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOroConfig_GlobalService extends KernelProdContainer
{
    /*
     * Gets the private 'oro_config.global' shared service.
     *
     * @return \Oro\Bundle\ConfigBundle\Config\ConfigManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/ConfigBundle/Config/ConfigManager.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['oro_config.global'])) {
            return $container->privates['oro_config.global'];
        }

        return $container->privates['oro_config.global'] = new \Oro\Bundle\ConfigBundle\Config\ConfigManager($a, ['pim_analytics' => ['version_update' => ['value' => true, 'scope' => 'app']], 'pim_ui' => ['language' => ['value' => 'en_US', 'scope' => 'app'], 'loading_message_enabled' => ['value' => false, 'scope' => 'app'], 'loading_messages' => ['value' => NULL, 'scope' => 'app']]]);
    }
}
