<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOroSecurity_Acl_AnnotationProvider_Cache_WarmerService extends KernelProdContainer
{
    /*
     * Gets the private 'oro_security.acl.annotation_provider.cache.warmer' shared service.
     *
     * @return \Oro\Bundle\SecurityBundle\Cache\AclAnnotationCacheWarmer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-kernel/CacheWarmer/CacheWarmerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/SecurityBundle/Cache/AclAnnotationCacheWarmer.php';

        return $container->privates['oro_security.acl.annotation_provider.cache.warmer'] = new \Oro\Bundle\SecurityBundle\Cache\AclAnnotationCacheWarmer(($container->privates['oro_security.acl.annotation_provider'] ?? $container->getOroSecurity_Acl_AnnotationProviderService()));
    }
}
