<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOroDatagrid_Extension_Action_Type_AjaxService extends KernelProdContainer
{
    /*
     * Gets the public 'oro_datagrid.extension.action.type.ajax' service.
     *
     * @return \Oro\Bundle\DataGridBundle\Extension\Action\Actions\AjaxAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/ActionInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/AbstractAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/DataGridBundle/Extension/Action/Actions/AjaxAction.php';

        $container->factories['oro_datagrid.extension.action.type.ajax'] = function () use ($container) {
            return new \Oro\Bundle\DataGridBundle\Extension\Action\Actions\AjaxAction();
        };

        return $container->factories['oro_datagrid.extension.action.type.ajax']();
    }
}
