<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimConnector_Reader_File_YamlJobInstanceService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_connector.reader.file.yaml_job_instance' shared service.
     *
     * @return \Akeneo\Tool\Component\Connector\Reader\File\Yaml\Reader
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Item/ItemReaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Item/FlushableInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Step/StepExecutionAwareInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/Reader/File/FileReaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Batch/Item/TrackableItemReaderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/Reader/File/Yaml/Reader.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/ArrayConverter/ArrayConverterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/ArrayConverter/DummyConverter.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Connector/ArrayConverter/FieldsRequirementChecker.php';

        return $container->privates['pim_connector.reader.file.yaml_job_instance'] = new \Akeneo\Tool\Component\Connector\Reader\File\Yaml\Reader(new \Akeneo\Tool\Component\Connector\ArrayConverter\DummyConverter(($container->privates['pim_connector.array_convertor.checker.fields_requirement'] ?? ($container->privates['pim_connector.array_convertor.checker.fields_requirement'] = new \Akeneo\Tool\Component\Connector\ArrayConverter\FieldsRequirementChecker())), [0 => 'code', 1 => 'type', 2 => 'connector', 3 => 'label', 4 => 'alias'], [0 => 'code', 1 => 'type', 2 => 'connector', 3 => 'label']), 'jobs');
    }
}
