<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Normalizer_Standard_AssociationTypeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.normalizer.standard.association_type' shared service.
     *
     * @return \Akeneo\Pim\Structure\Component\Normalizer\Standard\AssociationTypeNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Normalizer/Standard/AssociationTypeNormalizer.php';

        return $container->privates['pim_catalog.normalizer.standard.association_type'] = new \Akeneo\Pim\Structure\Component\Normalizer\Standard\AssociationTypeNormalizer(($container->privates['pim_catalog.normalizer.standard.translation'] ?? $container->load('getPimCatalog_Normalizer_Standard_TranslationService')));
    }
}
