<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Controller_Rest_GroupService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_enrich.controller.rest.group' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\GroupController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/GroupController.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/GroupViolationNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Remover/RemoverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Remover/BulkRemoverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/StorageUtilsBundle/Doctrine/Common/Remover/BaseRemover.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Command/GroupProductsHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/InternalApi/ConstraintViolationNormalizer.php';

        $a = ($container->privates['pim_catalog.repository.group'] ?? $container->load('getPimCatalog_Repository_GroupService'));
        $b = ($container->privates['pim_catalog.repository.product'] ?? $container->load('getPimCatalog_Repository_ProductService'));
        $c = ($container->privates['pim_internal_api_serializer'] ?? $container->load('getPimInternalApiSerializerService'));

        return $container->services['pim_enrich.controller.rest.group'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\GroupController($a, $b, $c, ($container->services['pim_user.context.user'] ?? $container->getPimUser_Context_UserService()), ($container->privates['pim_catalog.updater.group'] ?? $container->load('getPimCatalog_Updater_GroupService')), ($container->privates['pim_catalog.validator.product'] ?? $container->load('getPimCatalog_Validator_ProductService')), new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\GroupViolationNormalizer($c), ($container->privates['pim_catalog.saver.group'] ?? $container->load('getPimCatalog_Saver_GroupService')), new \Akeneo\Tool\Bundle\StorageUtilsBundle\Doctrine\Common\Remover\BaseRemover(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()), 'Akeneo\\Pim\\Enrichment\\Component\\Product\\Model\\Group'), ($container->privates['pim_catalog.factory.group'] ?? $container->load('getPimCatalog_Factory_GroupService')), ($container->privates['pim_enrich.normalizer.violation'] ?? ($container->privates['pim_enrich.normalizer.violation'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\InternalApi\ConstraintViolationNormalizer())), new \Akeneo\Pim\Enrichment\Component\Product\Command\GroupProductsHandler(($container->privates['Akeneo\\Pim\\Enrichment\\Component\\Product\\Query\\FindProductUuidsInGroup'] ?? $container->load('getFindProductUuidsInGroupService')), $a, ($container->privates['pim_catalog.saver.product'] ?? $container->load('getPimCatalog_Saver_ProductService')), $b, 100));
    }
}
