<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Updater_GroupService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.updater.group' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Updater\GroupUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Updater/ObjectUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Updater/GroupUpdater.php';

        return $container->privates['pim_catalog.updater.group'] = new \Akeneo\Pim\Enrichment\Component\Product\Updater\GroupUpdater(($container->privates['pim_catalog.repository.group_type'] ?? $container->load('getPimCatalog_Repository_GroupTypeService')), ($container->privates['pim_catalog.repository.attribute'] ?? $container->load('getPimCatalog_Repository_AttributeService')));
    }
}
