<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_EventListener_RemoveAttributeFilterInJobInstancesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_enrich.event_listener.remove_attribute_filter_in_job_instances' shared service.
     *
     * @return \Akeneo\Pim\Structure\Bundle\EventSubscriber\RemoveAttributeFiltersInJobInstancesOnAttributeDeletion
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/EventSubscriber/RemoveAttributeFiltersInJobInstancesOnAttributeDeletion.php';

        $a = ($container->privates['akeneo_batch.saver.job_instance'] ?? $container->load('getAkeneoBatch_Saver_JobInstanceService'));

        if (isset($container->privates['pim_enrich.event_listener.remove_attribute_filter_in_job_instances'])) {
            return $container->privates['pim_enrich.event_listener.remove_attribute_filter_in_job_instances'];
        }

        return $container->privates['pim_enrich.event_listener.remove_attribute_filter_in_job_instances'] = new \Akeneo\Pim\Structure\Bundle\EventSubscriber\RemoveAttributeFiltersInJobInstancesOnAttributeDeletion(($container->privates['akeneo_batch.job.job_instance_repository'] ?? $container->load('getAkeneoBatch_Job_JobInstanceRepositoryService')), $a);
    }
}
