<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPim_ReferenceData_Query_Filter_ReferenceDataService extends KernelProdContainer
{
    /*
     * Gets the private 'pim.reference_data.query.filter.reference_data' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\ReferenceDataFilter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/FilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/Filter/AttributeFilterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/AbstractAttributeFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/Filter/Attribute/ReferenceDataFilter.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/ReferenceData/ConfigurationRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/ReferenceData/ConfigurationRegistry.php';

        return $container->privates['pim.reference_data.query.filter.reference_data'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\Filter\Attribute\ReferenceDataFilter(($container->privates['pim_catalog.validator.helper.attribute_filter'] ?? $container->load('getPimCatalog_Validator_Helper_AttributeFilterService')), ($container->privates['pim_reference_data.repository_resolver'] ?? $container->load('getPimReferenceData_RepositoryResolverService')), ($container->privates['pim_reference_data.registry'] ?? ($container->privates['pim_reference_data.registry'] = new \Akeneo\Pim\Structure\Component\ReferenceData\ConfigurationRegistry())), [0 => 'pim_reference_data_simpleselect', 1 => 'pim_reference_data_multiselect'], [0 => 'IN', 1 => 'EMPTY', 2 => 'NOT EMPTY', 3 => 'NOT IN']);
    }
}
