<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Constraint_FileExtensionsAndMimetypesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.constraint.file_extensions_and_mimetypes' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\FileValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/FileValidator.php';

        return $container->privates['pim_catalog.validator.constraint.file_extensions_and_mimetypes'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\FileValidator($container->parameters['pim_catalog.validator.extension_to_mimetype_mapping']);
    }
}
