<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimUser_Normalizer_UserRoleService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_user.normalizer.user_role' shared service.
     *
     * @return \Akeneo\UserManagement\Component\Normalizer\RoleNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Component/Normalizer/RoleNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/SecurityBundle/Normalizer/AclPrivilegeNormalizer.php';

        $a = ($container->services['oro_security.acl.manager'] ?? $container->load('getOroSecurity_Acl_ManagerService'));

        if (isset($container->privates['pim_user.normalizer.user_role'])) {
            return $container->privates['pim_user.normalizer.user_role'];
        }

        return $container->privates['pim_user.normalizer.user_role'] = new \Akeneo\UserManagement\Component\Normalizer\RoleNormalizer($a, ($container->privates['oro_security.normalizer.acl_privilege'] ?? ($container->privates['oro_security.normalizer.acl_privilege'] = new \Oro\Bundle\SecurityBundle\Normalizer\AclPrivilegeNormalizer())));
    }
}
