<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_EventSubscriber_LoadProductQuantifiedAssociationsService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.event_subscriber.load_product_quantified_associations' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EntityWithQuantifiedAssociations\LoadEntitySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithQuantifiedAssociations/LoadEntitySubscriber.php';

        $a = ($container->privates['akeneo.pim.enrichment.product.query.quantified_association.get_uuid_mapping_query'] ?? $container->load('getAkeneo_Pim_Enrichment_Product_Query_QuantifiedAssociation_GetUuidMappingQueryService'));

        if (isset($container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'])) {
            return $container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'];
        }
        $b = ($container->privates['akeneo.pim.enrichment.product.query.quantified_association.get_id_mapping_from_product_model_ids_query'] ?? $container->load('getAkeneo_Pim_Enrichment_Product_Query_QuantifiedAssociation_GetIdMappingFromProductModelIdsQueryService'));

        if (isset($container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'])) {
            return $container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'];
        }
        $c = ($container->privates['akeneo.pim.enrichment.product.query.find_quantified_association_codes'] ?? $container->load('getAkeneo_Pim_Enrichment_Product_Query_FindQuantifiedAssociationCodesService'));

        if (isset($container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'])) {
            return $container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'];
        }

        return $container->privates['pim_catalog.event_subscriber.load_product_quantified_associations'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EntityWithQuantifiedAssociations\LoadEntitySubscriber($a, $b, $c);
    }
}
