<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Saver_ProductService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.saver.product' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Doctrine\Common\Saver\ProductSaver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Saver/SaverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Saver/BulkSaverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductSaver.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/Common/Saver/ProductUniqueDataSynchronizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Factory/ProductUniqueDataFactory.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['pim_catalog.saver.product'])) {
            return $container->privates['pim_catalog.saver.product'];
        }
        $b = ($container->services['event_dispatcher'] ?? $container->getEventDispatcherService());

        if (isset($container->privates['pim_catalog.saver.product'])) {
            return $container->privates['pim_catalog.saver.product'];
        }

        return $container->privates['pim_catalog.saver.product'] = new \Akeneo\Pim\Enrichment\Bundle\Doctrine\Common\Saver\ProductSaver($a, $b, new \Akeneo\Pim\Enrichment\Bundle\Doctrine\Common\Saver\ProductUniqueDataSynchronizer(new \Akeneo\Pim\Enrichment\Component\Product\Factory\ProductUniqueDataFactory('Akeneo\\Pim\\Enrichment\\Component\\Product\\Model\\ProductUniqueData'), ($container->privates['pim_catalog.repository.cached_attribute'] ?? $container->load('getPimCatalog_Repository_CachedAttributeService'))));
    }
}
