<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimFilter_Form_Type_Filter_PriceService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_filter.form.type.filter.price' shared service.
     *
     * @return \Oro\Bundle\PimFilterBundle\Form\Type\Filter\PriceFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimFilterBundle/Form/Type/Filter/PriceFilterType.php';

        return $container->privates['pim_filter.form.type.filter.price'] = new \Oro\Bundle\PimFilterBundle\Form\Type\Filter\PriceFilterType(($container->privates['pim_catalog.repository.currency'] ?? $container->load('getPimCatalog_Repository_CurrencyService')));
    }
}
