<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Controller_Rest_CategoryService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_enrich.controller.rest.category' shared service.
     *
     * @return \Akeneo\Category\Infrastructure\Controller\InternalApi\CategoryController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Category/back/Infrastructure/Controller/InternalApi/CategoryController.php';

        return $container->services['pim_enrich.controller.rest.category'] = new \Akeneo\Category\Infrastructure\Controller\InternalApi\CategoryController(($container->privates['pim_catalog.repository.category'] ?? $container->getPimCatalog_Repository_CategoryService()), ($container->privates['pim_enrich.twig.category_extension'] ?? $container->load('getPimEnrich_Twig_CategoryExtensionService')), ($container->privates['pim_internal_api_serializer'] ?? $container->load('getPimInternalApiSerializerService')), ($container->privates['pim_catalog.filter.chained'] ?? $container->load('getPimCatalog_Filter_ChainedService')));
    }
}
