<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimAnalytics_ExternalApi_Controller_GetSystemInformationService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_analytics.external_api.controller.get_system_information' shared service.
     *
     * @return \Akeneo\Platform\Bundle\AnalyticsBundle\Controller\ExternalApi\GetSystemInformationController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/AnalyticsBundle/Controller/ExternalApi/GetSystemInformationController.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/PimVersionBundle/Version/PimVersion.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/PimVersionBundle/Version/GrowthVersion.php';

        return $container->services['pim_analytics.external_api.controller.get_system_information'] = new \Akeneo\Platform\Bundle\AnalyticsBundle\Controller\ExternalApi\GetSystemInformationController(($container->services['pim_catalog.version_provider'] ?? $container->load('getPimCatalog_VersionProviderService')), ($container->services['Akeneo\\Platform\\Bundle\\PimVersionBundle\\Version\\GrowthVersion'] ?? ($container->services['Akeneo\\Platform\\Bundle\\PimVersionBundle\\Version\\GrowthVersion'] = new \Akeneo\Platform\Bundle\PimVersionBundle\Version\GrowthVersion())));
    }
}
