<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Normalizer_AttributeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_enrich.normalizer.attribute' shared service.
     *
     * @return \Akeneo\Pim\Structure\Component\Normalizer\InternalApi\AttributeNormalizer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Normalizer/InternalApi/AttributeNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Field/FieldProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Field/FieldChainedProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Field/WysiwygFieldProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Field/BaseFieldProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Field/ReferenceDataFieldProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/EmptyValue/EmptyValueProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/EmptyValue/EmptyValueChainedProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/EmptyValue/ReferenceDataEmptyValueProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/EmptyValue/BaseEmptyValueProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Filter/FilterProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Filter/FilterChainedProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Filter/BaseFilterProvider.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Provider/Filter/ReferenceDataFilterProvider.php';

        $a = ($container->privates['pim_standard_format_serializer'] ?? $container->load('getPimStandardFormatSerializerService'));

        if (isset($container->privates['pim_enrich.normalizer.attribute'])) {
            return $container->privates['pim_enrich.normalizer.attribute'];
        }
        $b = ($container->privates['pim_catalog.localization.localizer.number'] ?? $container->load('getPimCatalog_Localization_Localizer_NumberService'));

        if (isset($container->privates['pim_enrich.normalizer.attribute'])) {
            return $container->privates['pim_enrich.normalizer.attribute'];
        }
        $c = new \Akeneo\Platform\Bundle\UIBundle\Provider\Field\FieldChainedProvider();
        $c->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\Field\WysiwygFieldProvider());
        $c->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\Field\BaseFieldProvider());
        $c->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\Field\ReferenceDataFieldProvider());
        $d = new \Akeneo\Platform\Bundle\UIBundle\Provider\EmptyValue\EmptyValueChainedProvider();
        $d->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\EmptyValue\ReferenceDataEmptyValueProvider());
        $d->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\EmptyValue\BaseEmptyValueProvider());
        $e = new \Akeneo\Platform\Bundle\UIBundle\Provider\Filter\FilterChainedProvider();
        $e->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\Filter\BaseFilterProvider());
        $e->addProvider(new \Akeneo\Platform\Bundle\UIBundle\Provider\Filter\ReferenceDataFilterProvider());

        return $container->privates['pim_enrich.normalizer.attribute'] = new \Akeneo\Pim\Structure\Component\Normalizer\InternalApi\AttributeNormalizer($a, $c, $d, $e, $b);
    }
}
