<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_EventSubscriber_LoadProductValuesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.event_subscriber.load_product_values' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EntityWithValues\LoadEntityWithValuesSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/EntityWithValues/LoadEntityWithValuesSubscriber.php';

        $a = ($container->privates['akeneo.pim.enrichment.factory.write_value_collection'] ?? $container->load('getAkeneo_Pim_Enrichment_Factory_WriteValueCollectionService'));

        if (isset($container->privates['pim_catalog.event_subscriber.load_product_values'])) {
            return $container->privates['pim_catalog.event_subscriber.load_product_values'];
        }

        return $container->privates['pim_catalog.event_subscriber.load_product_values'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\EntityWithValues\LoadEntityWithValuesSubscriber($a);
    }
}
