<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPayloadFormatValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Component\Product\Validator\ExternalApi\PayloadFormatValidator' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Validator\ExternalApi\PayloadFormatValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Validator/ExternalApi/PayloadFormatValidator.php';

        return $container->privates['Akeneo\\Pim\\Enrichment\\Component\\Product\\Validator\\ExternalApi\\PayloadFormatValidator'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\ExternalApi\PayloadFormatValidator(($container->privates['pim_catalog.repository.attribute'] ?? $container->load('getPimCatalog_Repository_AttributeService')));
    }
}
