<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimUser_EventListener_UserPreferencesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_user.event_listener.user_preferences' shared service.
     *
     * @return \Akeneo\UserManagement\Bundle\EventListener\UserPreferencesListener
     */
    public static function do($container, $lazyLoad = true)
    {
        if ($lazyLoad) {
            return $container->privates['pim_user.event_listener.user_preferences'] = $container->createProxy('UserPreferencesListener_f335a33', function () use ($container) {
                return \UserPreferencesListener_f335a33::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) use ($container) {
                    $wrappedInstance = self::do($container, false);

                    $proxy->setProxyInitializer(null);

                    return true;
                });
            });
        }

        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Bundle/EventListener/UserPreferencesListener.php';

        return new \Akeneo\UserManagement\Bundle\EventListener\UserPreferencesListener(($container->privates['pim_catalog.repository.category'] ?? $container->getPimCatalog_Repository_CategoryService()), ($container->services['pim_catalog.repository.channel'] ?? $container->getPimCatalog_Repository_ChannelService()), ($container->privates['pim_catalog.repository.locale'] ?? $container->getPimCatalog_Repository_LocaleService()), ($container->privates['pim_user.repository.user'] ?? $container->load('getPimUser_Repository_UserService')));
    }
}
