<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Updater_Clearer_AssociationFieldService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.updater.clearer.association_field' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Updater\Clearer\Field\AssociationFieldClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/ClearerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Updater/Clearer/Field/AssociationFieldClearer.php';

        return $container->privates['pim_catalog.updater.clearer.association_field'] = new \Akeneo\Pim\Enrichment\Component\Product\Updater\Clearer\Field\AssociationFieldClearer(($container->privates['pim_catalog.association.two_way_association_updater'] ?? $container->load('getPimCatalog_Association_TwoWayAssociationUpdaterService')));
    }
}
