<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimDatagrid_Adapter_OroToPimGridFilterService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_datagrid.adapter.oro_to_pim_grid_filter' shared service.
     *
     * @return \Oro\Bundle\PimDataGridBundle\Adapter\OroToPimGridFilterAdapter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Adapter/GridFilterAdapterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Adapter/OroToPimGridFilterAdapter.php';

        return $container->privates['pim_datagrid.adapter.oro_to_pim_grid_filter'] = new \Oro\Bundle\PimDataGridBundle\Adapter\OroToPimGridFilterAdapter(($container->privates['pim_datagrid.extension.mass_action.dispatcher'] ?? $container->load('getPimDatagrid_Extension_MassAction_DispatcherService')));
    }
}
