<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Controller_Rest_LocaleService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_enrich.controller.rest.locale' shared service.
     *
     * @return \Akeneo\Channel\Infrastructure\Controller\InternalApi\LocaleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/back/Infrastructure/Controller/InternalApi/LocaleController.php';

        return $container->services['pim_enrich.controller.rest.locale'] = new \Akeneo\Channel\Infrastructure\Controller\InternalApi\LocaleController(($container->privates['pim_catalog.repository.locale'] ?? $container->getPimCatalog_Repository_LocaleService()), ($container->privates['pim_internal_api_serializer'] ?? $container->load('getPimInternalApiSerializerService')), ($container->privates['pim_catalog.filter.chained'] ?? $container->load('getPimCatalog_Filter_ChainedService')));
    }
}
