<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimVersioning_EventSubscriber_AddcontextService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_versioning.event_subscriber.addcontext' shared service.
     *
     * @return \Akeneo\Tool\Bundle\VersioningBundle\EventSubscriber\AddContextSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/VersioningBundle/EventSubscriber/AddContextSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/VersioningBundle/Manager/VersionContext.php';

        return $container->privates['pim_versioning.event_subscriber.addcontext'] = new \Akeneo\Tool\Bundle\VersioningBundle\EventSubscriber\AddContextSubscriber(($container->privates['pim_versioning.context.version'] ?? ($container->privates['pim_versioning.context.version'] = new \Akeneo\Tool\Bundle\VersioningBundle\Manager\VersionContext())));
    }
}
