<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimUser_Repository_RoleWithPermissionsService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_user.repository.role_with_permissions' shared service.
     *
     * @return \Akeneo\UserManagement\Bundle\Doctrine\ORM\Repository\RoleWithPermissionsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Bundle/Doctrine/ORM/Repository/RoleWithPermissionsRepository.php';

        return $container->services['pim_user.repository.role_with_permissions'] = new \Akeneo\UserManagement\Bundle\Doctrine\ORM\Repository\RoleWithPermissionsRepository(($container->services['pim_user.repository.role'] ?? $container->load('getPimUser_Repository_RoleService')), ($container->services['oro_security.acl.manager'] ?? $container->load('getOroSecurity_Acl_ManagerService')));
    }
}
