<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_EventSubscriber_SaveFamilyVariantsOnFamilyUpdateService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.event_subscriber.save_family_variants_on_family_update' shared service.
     *
     * @return \Akeneo\Pim\Structure\Bundle\EventSubscriber\SaveFamilyVariantOnFamilyUpdateSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/EventSubscriber/SaveFamilyVariantOnFamilyUpdateSubscriber.php';

        $a = ($container->services['.container.private.validator'] ?? $container->load('get_Container_Private_ValidatorService'));

        if (isset($container->privates['pim_catalog.event_subscriber.save_family_variants_on_family_update'])) {
            return $container->privates['pim_catalog.event_subscriber.save_family_variants_on_family_update'];
        }
        $b = ($container->privates['pim_catalog.saver.family_variant'] ?? $container->load('getPimCatalog_Saver_FamilyVariantService'));

        if (isset($container->privates['pim_catalog.event_subscriber.save_family_variants_on_family_update'])) {
            return $container->privates['pim_catalog.event_subscriber.save_family_variants_on_family_update'];
        }

        return $container->privates['pim_catalog.event_subscriber.save_family_variants_on_family_update'] = new \Akeneo\Pim\Structure\Bundle\EventSubscriber\SaveFamilyVariantOnFamilyUpdateSubscriber($a, $b, $b);
    }
}
