<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimDatagrid_Form_Type_DatagridViewService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_datagrid.form.type.datagrid_view' shared service.
     *
     * @return \Oro\Bundle\PimDataGridBundle\Form\Type\DatagridViewType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimDataGridBundle/Form/Type/DatagridViewType.php';

        return $container->privates['pim_datagrid.form.type.datagrid_view'] = new \Oro\Bundle\PimDataGridBundle\Form\Type\DatagridViewType('Oro\\Bundle\\PimDataGridBundle\\Entity\\DatagridView');
    }
}
