<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimNotification_EventSubscriber_JobExecutionNotifierService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_notification.event_subscriber.job_execution_notifier' shared service.
     *
     * @return \Akeneo\Platform\Bundle\NotificationBundle\EventSubscriber\JobExecutionNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/EventSubscriber/JobExecutionNotifier.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/Factory/NotificationFactoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/Factory/NotificationFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/NotificationBundle/Factory/AbstractNotificationFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/ImportExportBundle/Factory/NotificationFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/ImportExportBundle/Factory/MassEditNotificationFactory.php';

        $a = ($container->privates['pim_notification.notifier'] ?? $container->load('getPimNotification_NotifierService'));

        if (isset($container->privates['pim_notification.event_subscriber.job_execution_notifier'])) {
            return $container->privates['pim_notification.event_subscriber.job_execution_notifier'];
        }
        $b = new \Akeneo\Platform\Bundle\NotificationBundle\Factory\NotificationFactoryRegistry();
        $b->register(new \Akeneo\Platform\Bundle\ImportExportBundle\Factory\NotificationFactory([0 => 'import', 1 => 'export'], 'Akeneo\\Platform\\Bundle\\NotificationBundle\\Entity\\Notification'));
        $b->register(new \Akeneo\Platform\Bundle\ImportExportBundle\Factory\MassEditNotificationFactory([0 => 'quick_export', 1 => 'mass_edit', 2 => 'mass_delete'], 'Akeneo\\Platform\\Bundle\\NotificationBundle\\Entity\\Notification'));

        return $container->privates['pim_notification.event_subscriber.job_execution_notifier'] = new \Akeneo\Platform\Bundle\NotificationBundle\EventSubscriber\JobExecutionNotifier($b, $a);
    }
}
