<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Controller_Rest_ValueService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_enrich.controller.rest.value' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ValuesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Controller/InternalApi/ValuesController.php';

        return $container->services['pim_enrich.controller.rest.value'] = new \Akeneo\Pim\Enrichment\Bundle\Controller\InternalApi\ValuesController(($container->privates['pim_catalog.builder.product'] ?? $container->load('getPimCatalog_Builder_ProductService')), ($container->services['pim_user.context.user'] ?? $container->getPimUser_Context_UserService()), ($container->privates['pim_enrich.converter.enrich_to_standard.product_value'] ?? $container->load('getPimEnrich_Converter_EnrichToStandard_ProductValueService')), ($container->privates['pim_catalog.localization.localizer.converter'] ?? $container->load('getPimCatalog_Localization_Localizer_ConverterService')), ($container->privates['pim_catalog.updater.product'] ?? $container->load('getPimCatalog_Updater_ProductService')), ($container->privates['pim_catalog.validator.product'] ?? $container->load('getPimCatalog_Validator_ProductService')), ($container->privates['pim_catalog.repository.attribute'] ?? $container->load('getPimCatalog_Repository_AttributeService')), ($container->privates['pim_enrich.normalizer.product_violation'] ?? $container->load('getPimEnrich_Normalizer_ProductViolationService')), ($container->privates['pim_catalog.comparator.filter.product'] ?? $container->load('getPimCatalog_Comparator_Filter_ProductService')));
    }
}
