<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Doctrine_Query_FindVariantProductCompletenessService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.doctrine.query.find_variant_product_completeness' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Storage\Sql\Completeness\VariantProductRatio
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/ProductModel/Query/VariantProductRatioInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Storage/Sql/Completeness/VariantProductRatio.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['pim_catalog.doctrine.query.find_variant_product_completeness'])) {
            return $container->privates['pim_catalog.doctrine.query.find_variant_product_completeness'];
        }

        return $container->privates['pim_catalog.doctrine.query.find_variant_product_completeness'] = new \Akeneo\Pim\Enrichment\Bundle\Storage\Sql\Completeness\VariantProductRatio($a);
    }
}
