<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Updater_AttributeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.updater.attribute' shared service.
     *
     * @return \Akeneo\Pim\Structure\Component\Updater\AttributeUpdater
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Updater/ObjectUpdaterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Updater/AttributeUpdater.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/Localization/TranslatableUpdater.php';

        $a = ($container->privates['pim_catalog.repository.attribute_group'] ?? $container->load('getPimCatalog_Repository_AttributeGroupService'));

        if (isset($container->privates['pim_catalog.updater.attribute'])) {
            return $container->privates['pim_catalog.updater.attribute'];
        }

        return $container->privates['pim_catalog.updater.attribute'] = new \Akeneo\Pim\Structure\Component\Updater\AttributeUpdater($a, ($container->privates['pim_catalog.repository.locale'] ?? $container->getPimCatalog_Repository_LocaleService()), ($container->services['pim_catalog.registry.attribute_type'] ?? $container->load('getPimCatalog_Registry_AttributeTypeService')), ($container->privates['pim_structure.updater.translatable'] ?? ($container->privates['pim_structure.updater.translatable'] = new \Akeneo\Tool\Component\Localization\TranslatableUpdater())), [0 => 'auto_option_sorting', 1 => 'is_read_only', 2 => 'default_value'], [0 => 'group_labels']);
    }
}
