<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Repository_ProductModelService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.repository.product_model' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Doctrine\ORM\Repository\ProductModelRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Component/StorageUtils/Repository/CursorableRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Repository/ProductModelRepositoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Repository/ProductModelRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['pim_catalog.repository.product_model'])) {
            return $container->privates['pim_catalog.repository.product_model'];
        }

        return $container->privates['pim_catalog.repository.product_model'] = $a->getRepository('Akeneo\\Pim\\Enrichment\\Component\\Product\\Model\\ProductModel');
    }
}
