<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimStorageSerializerService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_storage_serializer' shared service.
     *
     * @return \Symfony\Component\Serializer\Serializer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/SerializerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/ContextAwareNormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/DenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/ContextAwareDenormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Encoder/EncoderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Encoder/ContextAwareEncoderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Encoder/DecoderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Encoder/ContextAwareDecoderInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Serializer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/CacheableSupportsMethodInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/ProductNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/PropertiesNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/AssociationsNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/PriceNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/Product/MetricNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/DateTimeNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Storage/FileNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Normalizer/Storage/AttributeOptionNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/PriceNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/Product/MetricNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/DateTimeNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Normalizer/Standard/FileNormalizer.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Encoder/JsonEncoder.php';

        $a = ($container->privates['pim_catalog.normalizer.standard.product.properties'] ?? $container->load('getPimCatalog_Normalizer_Standard_Product_PropertiesService'));

        if (isset($container->privates['pim_storage_serializer'])) {
            return $container->privates['pim_storage_serializer'];
        }
        $b = ($container->privates['pim_catalog.normalizer.standard.product.associations'] ?? $container->load('getPimCatalog_Normalizer_Standard_Product_AssociationsService'));

        if (isset($container->privates['pim_storage_serializer'])) {
            return $container->privates['pim_storage_serializer'];
        }
        $c = ($container->privates['pim_catalog.normalizer.storage.product.product_values'] ?? $container->load('getPimCatalog_Normalizer_Storage_Product_ProductValuesService'));

        if (isset($container->privates['pim_storage_serializer'])) {
            return $container->privates['pim_storage_serializer'];
        }
        $d = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\PropertiesNormalizer($a);
        $e = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\AssociationsNormalizer($b);
        $f = ($container->privates['pim_catalog.normalizer.storage.product.product_value'] ?? $container->load('getPimCatalog_Normalizer_Storage_Product_ProductValueService'));

        if (isset($container->privates['pim_storage_serializer'])) {
            return $container->privates['pim_storage_serializer'];
        }

        return $container->privates['pim_storage_serializer'] = new \Symfony\Component\Serializer\Serializer([0 => new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\ProductNormalizer($d, $e), 1 => $c, 2 => $f, 3 => new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\PriceNormalizer(($container->privates['pim_catalog.normalizer.standard.product.price'] ?? ($container->privates['pim_catalog.normalizer.standard.product.price'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\Product\PriceNormalizer()))), 4 => new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\Product\MetricNormalizer(($container->privates['pim_catalog.normalizer.standard.product.metric'] ?? ($container->privates['pim_catalog.normalizer.standard.product.metric'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\Product\MetricNormalizer()))), 5 => new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\DateTimeNormalizer(($container->privates['pim_catalog.normalizer.standard.datetime'] ?? ($container->privates['pim_catalog.normalizer.standard.datetime'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\DateTimeNormalizer()))), 6 => new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Storage\FileNormalizer(($container->privates['pim_catalog.normalizer.standard.file'] ?? ($container->privates['pim_catalog.normalizer.standard.file'] = new \Akeneo\Pim\Enrichment\Component\Product\Normalizer\Standard\FileNormalizer()))), 7 => new \Akeneo\Pim\Structure\Component\Normalizer\Storage\AttributeOptionNormalizer(($container->privates['pim_catalog.normalizer.standard.attribute_option'] ?? $container->load('getPimCatalog_Normalizer_Standard_AttributeOptionService'))), 8 => $d, 9 => $e], [0 => ($container->privates['serializer.encoder.json'] ?? ($container->privates['serializer.encoder.json'] = new \Symfony\Component\Serializer\Encoder\JsonEncoder()))]);
    }
}
