<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimUser_Form_Type_GroupService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_user.form.type.group' shared service.
     *
     * @return \Akeneo\UserManagement\Bundle\Form\Type\GroupType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/UserManagement/Bundle/Form/Type/GroupType.php';

        return $container->privates['pim_user.form.type.group'] = new \Akeneo\UserManagement\Bundle\Form\Type\GroupType();
    }
}
