<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimApi_Controller_GetMeasurementFamiliesService extends KernelProdContainer
{
    /*
     * Gets the public 'pim_api.controller.get_measurement_families' shared service.
     *
     * @return \Akeneo\Tool\Bundle\MeasureBundle\Controller\ExternalApi\GetMeasurementFamiliesAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/MeasureBundle/Controller/ExternalApi/GetMeasurementFamiliesAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/serializer/Normalizer/NormalizerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/MeasureBundle/Normalizer/ExternalMeasurementFamilyNormalizer.php';

        return $container->services['pim_api.controller.get_measurement_families'] = new \Akeneo\Tool\Bundle\MeasureBundle\Controller\ExternalApi\GetMeasurementFamiliesAction(($container->privates['akeneo_measure.persistence.measurement_family_repository'] ?? $container->load('getAkeneoMeasure_Persistence_MeasurementFamilyRepositoryService')), new \Akeneo\Tool\Bundle\MeasureBundle\Normalizer\ExternalMeasurementFamilyNormalizer());
    }
}
