<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Resolver_LocaleService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_enrich.resolver.locale' shared service.
     *
     * @return \Akeneo\Platform\Bundle\UIBundle\Resolver\LocaleResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Resolver/LocaleResolver.php';

        return $container->privates['pim_enrich.resolver.locale'] = new \Akeneo\Platform\Bundle\UIBundle\Resolver\LocaleResolver(($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), $container->getEnv('APP_DEFAULT_LOCALE'));
    }
}
