<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimFilter_Form_Type_DatetimeRangeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_filter.form.type.datetime_range' shared service.
     *
     * @return \Oro\Bundle\PimFilterBundle\Form\Type\DateTimeRangeType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Oro/Bundle/PimFilterBundle/Form/Type/DateTimeRangeType.php';

        return $container->privates['pim_filter.form.type.datetime_range'] = new \Oro\Bundle\PimFilterBundle\Form\Type\DateTimeRangeType();
    }
}
