<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimUi_Form_Type_DateService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_ui.form.type.date' shared service.
     *
     * @return \Akeneo\Platform\Bundle\UIBundle\Form\Type\DateType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Platform/Bundle/UIBundle/Form/Type/DateType.php';

        return $container->privates['pim_ui.form.type.date'] = new \Akeneo\Platform\Bundle\UIBundle\Form\Type\DateType(($container->privates['pim_enrich.resolver.locale'] ?? $container->load('getPimEnrich_Resolver_LocaleService')), ($container->privates['pim_catalog.localization.factory.date'] ?? $container->load('getPimCatalog_Localization_Factory_DateService')));
    }
}
