<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Helper_AttributeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.helper.attribute' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Validator\AttributeValidatorHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Validator/AttributeValidatorHelper.php';

        return $container->privates['pim_catalog.validator.helper.attribute'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\AttributeValidatorHelper(($container->privates['pim_catalog.repository.locale'] ?? $container->getPimCatalog_Repository_LocaleService()), ($container->services['pim_catalog.repository.channel'] ?? $container->getPimCatalog_Repository_ChannelService()));
    }
}
