<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Query_ProductIdentifierQueryBuilderFactoryService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.query.product_identifier_query_builder_factory' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\ProductQueryBuilderFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/ProductQueryBuilderFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Elasticsearch/ProductQueryBuilderFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/ProductQueryBuilderOptionsResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Query/ProductQueryBuilderOptionsResolver.php';

        $a = ($container->privates['pim_catalog.query.filter.product_registry'] ?? $container->load('getPimCatalog_Query_Filter_ProductRegistryService'));

        if (isset($container->privates['pim_catalog.query.product_identifier_query_builder_factory'])) {
            return $container->privates['pim_catalog.query.product_identifier_query_builder_factory'];
        }

        return $container->privates['pim_catalog.query.product_identifier_query_builder_factory'] = new \Akeneo\Pim\Enrichment\Bundle\Elasticsearch\ProductQueryBuilderFactory('Akeneo\\Pim\\Enrichment\\Component\\Product\\Query\\ProductQueryBuilder', ($container->privates['pim_catalog.repository.attribute'] ?? $container->load('getPimCatalog_Repository_AttributeService')), $a, ($container->privates['pim_catalog.query.sorter.registry'] ?? $container->load('getPimCatalog_Query_Sorter_RegistryService')), ($container->privates['pim_catalog.factory.product_and_product_model_identifier_cursor'] ?? $container->load('getPimCatalog_Factory_ProductAndProductModelIdentifierCursorService')), ($container->privates['pim_catalog.query.product_query_builder_resolver'] ?? ($container->privates['pim_catalog.query.product_query_builder_resolver'] = new \Akeneo\Pim\Enrichment\Component\Product\Query\ProductQueryBuilderOptionsResolver())));
    }
}
