<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimEnrich_Doctrine_Counter_CategoryProductService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_enrich.doctrine.counter.category_product' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Doctrine\ORM\Counter\CategoryProductsCounter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Counter/CategoryItemsCounterInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ORM/Counter/CategoryProductsCounter.php';

        $a = ($container->privates['pim_catalog.query.product_identifier_query_builder_factory'] ?? $container->load('getPimCatalog_Query_ProductIdentifierQueryBuilderFactoryService'));

        if (isset($container->privates['pim_enrich.doctrine.counter.category_product'])) {
            return $container->privates['pim_enrich.doctrine.counter.category_product'];
        }

        return $container->privates['pim_enrich.doctrine.counter.category_product'] = new \Akeneo\Pim\Enrichment\Bundle\Doctrine\ORM\Counter\CategoryProductsCounter($a, ($container->privates['pim_catalog.repository.category'] ?? $container->getPimCatalog_Repository_CategoryService()));
    }
}
