<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Constraints_IsCurrencyActivatedService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.constraints.is_currency_activated' shared service.
     *
     * @return \Akeneo\Channel\Infrastructure\Component\Validator\Constraint\IsCurrencyActivatedValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Channel/back/Infrastructure/Component/Validator/Constraint/IsCurrencyActivatedValidator.php';

        return $container->privates['pim_catalog.validator.constraints.is_currency_activated'] = new \Akeneo\Channel\Infrastructure\Component\Validator\Constraint\IsCurrencyActivatedValidator();
    }
}
