<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_EventSubscriber_AddUniqueAttributesToVariantProductAttributeSetService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.event_subscriber.add_unique_attributes_to_variant_product_attribute_set' shared service.
     *
     * @return \Akeneo\Pim\Structure\Bundle\EventSubscriber\AddUniqueAttributesToVariantProductAttributeSetSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/EventSubscriber/AddUniqueAttributesToVariantProductAttributeSetSubscriber.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/FamilyVariant/AddUniqueAttributes.php';

        return $container->privates['pim_catalog.event_subscriber.add_unique_attributes_to_variant_product_attribute_set'] = new \Akeneo\Pim\Structure\Bundle\EventSubscriber\AddUniqueAttributesToVariantProductAttributeSetSubscriber(new \Akeneo\Pim\Structure\Component\FamilyVariant\AddUniqueAttributes());
    }
}
