<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimReferenceData_RepositoryResolverService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_reference_data.repository_resolver' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\Doctrine\ReferenceDataRepositoryResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Repository/ReferenceDataRepositoryResolverInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Doctrine/ReferenceDataRepositoryResolver.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/ReferenceData/ConfigurationRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/ReferenceData/ConfigurationRegistry.php';

        return $container->privates['pim_reference_data.repository_resolver'] = new \Akeneo\Pim\Enrichment\Bundle\Doctrine\ReferenceDataRepositoryResolver(($container->privates['pim_reference_data.registry'] ?? ($container->privates['pim_reference_data.registry'] = new \Akeneo\Pim\Structure\Component\ReferenceData\ConfigurationRegistry())), ($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
