<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Constraint_BlacklistedAttributeCodeService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.constraint.blacklisted_attribute_code' shared service.
     *
     * @return \Akeneo\Pim\Structure\Component\Validator\Constraints\BlacklistedAttributeCodeValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Validator/Constraints/BlacklistedAttributeCodeValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Query/InternalApi/IsAttributeCodeBlacklistedInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/IsAttributeCodeBlacklisted.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Component/Query/InternalApi/GetBlacklistedAttributeJobExecutionIdInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Structure/Bundle/Query/InternalApi/Attribute/GetBlacklistedAttributeJobExecutionId.php';

        $a = ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService());

        if (isset($container->privates['pim_catalog.validator.constraint.blacklisted_attribute_code'])) {
            return $container->privates['pim_catalog.validator.constraint.blacklisted_attribute_code'];
        }

        return $container->privates['pim_catalog.validator.constraint.blacklisted_attribute_code'] = new \Akeneo\Pim\Structure\Component\Validator\Constraints\BlacklistedAttributeCodeValidator(new \Akeneo\Pim\Structure\Bundle\Query\InternalApi\Attribute\IsAttributeCodeBlacklisted($a), new \Akeneo\Pim\Structure\Bundle\Query\InternalApi\Attribute\GetBlacklistedAttributeJobExecutionId($a), ($container->privates['translator.default'] ?? $container->getTranslator_DefaultService()), ($container->services['router'] ?? $container->getRouterService()));
    }
}
