<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPurgeOutdatedDataService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Automation\DataQualityInsights\Application\Consolidation\PurgeOutdatedData' shared service.
     *
     * @return \Akeneo\Pim\Automation\DataQualityInsights\Application\Consolidation\PurgeOutdatedData
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Automation/DataQualityInsights/back/Application/Consolidation/PurgeOutdatedData.php';

        $a = ($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Infrastructure\\Persistence\\Repository\\DashboardScoresProjectionRepository'] ?? $container->load('getDashboardScoresProjectionRepositoryService'));

        if (isset($container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Application\\Consolidation\\PurgeOutdatedData'])) {
            return $container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Application\\Consolidation\\PurgeOutdatedData'];
        }

        return $container->privates['Akeneo\\Pim\\Automation\\DataQualityInsights\\Application\\Consolidation\\PurgeOutdatedData'] = new \Akeneo\Pim\Automation\DataQualityInsights\Application\Consolidation\PurgeOutdatedData($a);
    }
}
