<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Constraint_LocalizableValuesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.constraint.localizable_values' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\LocalizableValuesValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/LocalizableValuesValidator.php';

        $a = ($container->privates['akeneo.pim.structure.query.get_attributes'] ?? $container->load('getAkeneo_Pim_Structure_Query_GetAttributesService'));

        if (isset($container->privates['pim_catalog.validator.constraint.localizable_values'])) {
            return $container->privates['pim_catalog.validator.constraint.localizable_values'];
        }

        return $container->privates['pim_catalog.validator.constraint.localizable_values'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\LocalizableValuesValidator(($container->privates['pim_catalog.repository.cached_locale'] ?? $container->load('getPimCatalog_Repository_CachedLocaleService')), ($container->privates['pim_catalog.repository.cached_channel'] ?? $container->load('getPimCatalog_Repository_CachedChannelService')), $a);
    }
}
