<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPimCatalog_Validator_Constraint_NotEmptyVariantAxesService extends KernelProdContainer
{
    /*
     * Gets the private 'pim_catalog.validator.constraint.not_empty_variant_axes' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\NotEmptyVariantAxesValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/Validator/Constraints/NotEmptyVariantAxesValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Component/Product/EntityWithFamilyVariant/EntityWithFamilyVariantAttributesProvider.php';

        return $container->privates['pim_catalog.validator.constraint.not_empty_variant_axes'] = new \Akeneo\Pim\Enrichment\Component\Product\Validator\Constraints\NotEmptyVariantAxesValidator(($container->privates['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] ?? ($container->privates['pim_catalog.family_variant.provider.entity_with_family_variant_attributes'] = new \Akeneo\Pim\Enrichment\Component\Product\EntityWithFamilyVariant\EntityWithFamilyVariantAttributesProvider())));
    }
}
