<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReindexFormerAncestorsSubscriberService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Bundle\EventSubscriber\Product\OnSave\ReindexFormerAncestorsSubscriber' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\Product\OnSave\ReindexFormerAncestorsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/EventSubscriber/Product/OnSave/ReindexFormerAncestorsSubscriber.php';

        $a = ($container->privates['akeneo.pim.enrichment.product.query.get_ancestor_and_descendant_product_model_codes'] ?? $container->load('getAkeneo_Pim_Enrichment_Product_Query_GetAncestorAndDescendantProductModelCodesService'));

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\Product\\OnSave\\ReindexFormerAncestorsSubscriber'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\Product\\OnSave\\ReindexFormerAncestorsSubscriber'];
        }
        $b = ($container->services['pim_catalog.elasticsearch.indexer.product_model'] ?? $container->load('getPimCatalog_Elasticsearch_Indexer_ProductModelService'));

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\Product\\OnSave\\ReindexFormerAncestorsSubscriber'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\Product\\OnSave\\ReindexFormerAncestorsSubscriber'];
        }

        return $container->privates['Akeneo\\Pim\\Enrichment\\Bundle\\EventSubscriber\\Product\\OnSave\\ReindexFormerAncestorsSubscriber'] = new \Akeneo\Pim\Enrichment\Bundle\EventSubscriber\Product\OnSave\ReindexFormerAncestorsSubscriber($a, $b);
    }
}
