<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegeneratePasswordActionService extends KernelProdContainer
{
    /*
     * Gets the public 'Akeneo\Connectivity\Connection\Infrastructure\Connections\Controller\Internal\RegeneratePasswordAction' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\Connections\Controller\Internal\RegeneratePasswordAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Connections/Controller/Internal/RegeneratePasswordAction.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Settings/Command/RegenerateConnectionPasswordHandler.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Application/Settings/Service/RegenerateUserPasswordInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Service/User/RegenerateUserPassword.php';

        return $container->services['Akeneo\\Connectivity\\Connection\\Infrastructure\\Connections\\Controller\\Internal\\RegeneratePasswordAction'] = new \Akeneo\Connectivity\Connection\Infrastructure\Connections\Controller\Internal\RegeneratePasswordAction(new \Akeneo\Connectivity\Connection\Application\Settings\Command\RegenerateConnectionPasswordHandler(($container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Settings\\Persistence\\DbalConnectionRepository'] ?? $container->load('getDbalConnectionRepositoryService')), new \Akeneo\Connectivity\Connection\Infrastructure\Service\User\RegenerateUserPassword(($container->privates['pim_user.manager'] ?? $container->load('getPimUser_ManagerService')), ($container->services['doctrine.dbal.default_connection'] ?? $container->getDoctrine_Dbal_DefaultConnectionService()))), ($container->privates['oro_security.security_facade'] ?? $container->getOroSecurity_SecurityFacadeService()));
    }
}
