<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserShouldExistValidatorService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\UserShouldExistValidator' shared service.
     *
     * @return \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\UserShouldExistValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Product/back/Infrastructure/Validation/UserShouldExistValidator.php';

        $a = ($container->privates['pim_user.repository.user'] ?? $container->load('getPimUser_Repository_UserService'));

        if (isset($container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\UserShouldExistValidator'])) {
            return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\UserShouldExistValidator'];
        }

        return $container->privates['Akeneo\\Pim\\Enrichment\\Product\\Infrastructure\\Validation\\UserShouldExistValidator'] = new \Akeneo\Pim\Enrichment\Product\Infrastructure\Validation\UserShouldExistValidator($a);
    }
}
