<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateCatalogActionService extends KernelProdContainer
{
    /*
     * Gets the public 'Akeneo\Catalogs\Infrastructure\Controller\Internal\UpdateCatalogAction' shared autowired service.
     *
     * @return \Akeneo\Catalogs\Infrastructure\Controller\Internal\UpdateCatalogAction
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/components/catalogs/back/src/Infrastructure/Controller/Internal/UpdateCatalogAction.php';

        return $container->services['Akeneo\\Catalogs\\Infrastructure\\Controller\\Internal\\UpdateCatalogAction'] = new \Akeneo\Catalogs\Infrastructure\Controller\Internal\UpdateCatalogAction(($container->services['.container.private.validator'] ?? $container->load('get_Container_Private_ValidatorService')), ($container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Catalog\\GetCatalogQuery'] ?? $container->load('getGetCatalogQueryService')), ($container->privates['Akeneo\\Catalogs\\Infrastructure\\Persistence\\Catalog\\UpsertCatalogQuery'] ?? $container->load('getUpsertCatalogQueryService')), ($container->services['.container.private.serializer'] ?? $container->load('get_Container_Private_SerializerService')));
    }
}
