<?php

namespace ContainerRWxfJwK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebMarketplaceApiService extends KernelProdContainer
{
    /*
     * Gets the private 'Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceApi' shared service.
     *
     * @return \Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceApi
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceApiInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Marketplace/WebMarketplaceApi.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/psr/http-client/src/ClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/ClientTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/guzzlehttp/guzzle/src/Client.php';

        $container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Marketplace\\WebMarketplaceApi'] = $instance = new \Akeneo\Connectivity\Connection\Infrastructure\Marketplace\WebMarketplaceApi(new \GuzzleHttp\Client(['base_uri' => 'https://api.apps.akeneo.cloud', 'headers' => ['User-Agent' => NULL]]), ($container->privates['Akeneo\\Connectivity\\Connection\\Infrastructure\\Marketplace\\WebMarketplaceAliases'] ?? $container->load('getWebMarketplaceAliasesService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')), ($container->services['akeneo_connectivity.connection.marketplace_fake_apps.feature'] ?? ($container->services['akeneo_connectivity.connection.marketplace_fake_apps.feature'] = new \Akeneo\Platform\Bundle\FeatureFlagBundle\Configuration\EnvVarFeatureFlag($container->getEnv('bool:FLAG_MARKETPLACE_FAKE_APPS_ENABLED')))));

        $instance->setFixturePath((\dirname(__DIR__, 4).'/vendor/akeneo/pim-community-dev/src/Akeneo/Connectivity/Connection/back/Infrastructure/Symfony/DependencyInjection/../Resources/fixtures/'));

        return $instance;
    }
}
