<?php

namespace Proxies\__CG__\Akeneo\Tool\Component\Batch\Model;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StepExecution extends \Akeneo\Tool\Component\Batch\Model\StepExecution implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'id', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'jobExecution', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'stepName', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'status', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'readCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'writeCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'filterCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'warningCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'startTime', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'endTime', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'executionContext', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitStatus', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitCode', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitDescription', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'terminateOnly', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'failureExceptions', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'errors', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'warnings', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'summary', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'trackingData', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'isTrackable'];
        }

        return ['__isInitialized__', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'id', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'jobExecution', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'stepName', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'status', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'readCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'writeCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'filterCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'warningCount', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'startTime', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'endTime', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'executionContext', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitStatus', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitCode', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'exitDescription', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'terminateOnly', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'failureExceptions', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'errors', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'warnings', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'summary', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'trackingData', '' . "\0" . 'Akeneo\\Tool\\Component\\Batch\\Model\\StepExecution' . "\0" . 'isTrackable'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (StepExecution $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * {@inheritDoc}
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);

        parent::__clone();
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getExecutionContext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExecutionContext', []);

        return parent::getExecutionContext();
    }

    /**
     * {@inheritDoc}
     */
    public function setExecutionContext(\Akeneo\Tool\Component\Batch\Item\ExecutionContext $executionContext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExecutionContext', [$executionContext]);

        return parent::setExecutionContext($executionContext);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndTime', []);

        return parent::getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndTime(\DateTime $endTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndTime', [$endTime]);

        return parent::setEndTime($endTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getReadCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReadCount', []);

        return parent::getReadCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setReadCount($readCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReadCount', [$readCount]);

        return parent::setReadCount($readCount);
    }

    /**
     * {@inheritDoc}
     */
    public function incrementReadCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementReadCount', []);

        return parent::incrementReadCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getWriteCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWriteCount', []);

        return parent::getWriteCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setWriteCount($writeCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWriteCount', [$writeCount]);

        return parent::setWriteCount($writeCount);
    }

    /**
     * {@inheritDoc}
     */
    public function incrementWriteCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementWriteCount', []);

        return parent::incrementWriteCount();
    }

    /**
     * {@inheritDoc}
     */
    public function getFilterCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFilterCount', []);

        return parent::getFilterCount();
    }

    /**
     * {@inheritDoc}
     */
    public function isTerminateOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTerminateOnly', []);

        return parent::isTerminateOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminateOnly()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminateOnly', []);

        return parent::setTerminateOnly();
    }

    /**
     * {@inheritDoc}
     */
    public function getStartTime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartTime', []);

        return parent::getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartTime(\DateTime $startTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartTime', [$startTime]);

        return parent::setStartTime($startTime);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\Akeneo\Tool\Component\Batch\Job\BatchStatus $status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function upgradeStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upgradeStatus', [$status]);

        return parent::upgradeStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStepName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStepName', []);

        return parent::getStepName();
    }

    /**
     * {@inheritDoc}
     */
    public function setExitStatus(\Akeneo\Tool\Component\Batch\Job\ExitStatus $exitStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExitStatus', [$exitStatus]);

        return parent::setExitStatus($exitStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getExitStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExitStatus', []);

        return parent::getExitStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getJobExecution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobExecution', []);

        return parent::getJobExecution();
    }

    /**
     * {@inheritDoc}
     */
    public function getJobParameters()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJobParameters', []);

        return parent::getJobParameters();
    }

    /**
     * {@inheritDoc}
     */
    public function getFailureExceptions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFailureExceptions', []);

        return parent::getFailureExceptions();
    }

    /**
     * {@inheritDoc}
     */
    public function addFailureException(\Exception $e)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFailureException', [$e]);

        return parent::addFailureException($e);
    }

    /**
     * {@inheritDoc}
     */
    public function getFailureExceptionMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFailureExceptionMessages', []);

        return parent::getFailureExceptionMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addError($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addError', [$message]);

        return parent::addError($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getErrors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getErrors', []);

        return parent::getErrors();
    }

    /**
     * {@inheritDoc}
     */
    public function addWarning($reason, array $reasonParameters, \Akeneo\Tool\Component\Batch\Item\InvalidItemInterface $item)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWarning', [$reason, $reasonParameters, $item]);

        return parent::addWarning($reason, $reasonParameters, $item);
    }

    /**
     * {@inheritDoc}
     */
    public function getWarnings()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWarnings', []);

        return parent::getWarnings();
    }

    /**
     * {@inheritDoc}
     */
    public function getWarningCount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWarningCount', []);

        return parent::getWarningCount();
    }

    /**
     * {@inheritDoc}
     */
    public function addSummaryInfo($key, $info)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSummaryInfo', [$key, $info]);

        return parent::addSummaryInfo($key, $info);
    }

    /**
     * {@inheritDoc}
     */
    public function incrementSummaryInfo($key, $increment = 1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementSummaryInfo', [$key, $increment]);

        return parent::incrementSummaryInfo($key, $increment);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummaryInfo($key, mixed $defaultValue = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummaryInfo', [$key, $defaultValue]);

        return parent::getSummaryInfo($key, $defaultValue);
    }

    /**
     * {@inheritDoc}
     */
    public function setSummary($summary)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSummary', [$summary]);

        return parent::setSummary($summary);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummary()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummary', []);

        return parent::getSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalItems(int $totalItems): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalItems', [$totalItems]);

        parent::setTotalItems($totalItems);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalItems(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalItems', []);

        return parent::getTotalItems();
    }

    /**
     * {@inheritDoc}
     */
    public function incrementProcessedItems(int $increment = 1): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'incrementProcessedItems', [$increment]);

        parent::incrementProcessedItems($increment);
    }

    /**
     * {@inheritDoc}
     */
    public function getProcessedItems(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProcessedItems', []);

        return parent::getProcessedItems();
    }

    /**
     * {@inheritDoc}
     */
    public function getTrackingData(): array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrackingData', []);

        return parent::getTrackingData();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrackingData(array $trackingData): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrackingData', [$trackingData]);

        parent::setTrackingData($trackingData);
    }

    /**
     * {@inheritDoc}
     */
    public function isTrackable(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isTrackable', []);

        return parent::isTrackable();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsTrackable(bool $trackable): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsTrackable', [$trackable]);

        parent::setIsTrackable($trackable);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
